apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        # Use `docker/podman images` command to get this
        image: docker.io/jcdiamantegcash/python-app-demo:v2 
        ports:
        - containerPort: 5000
